[project]
name = "122-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cssselect>=1.2.0",
    "httpx[cli]>=0.28.1",
    "ipdb>=0.13.13",
    "ipython>=8.31.0",
    "lxml>=5.3.0",
    "ruff>=0.8.6",
]
